version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: script/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: script/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: script/stop_server.sh
      timeout: 300
      runas: root

#version: 0.0
#os: linux
#files:
#  - source: /index.html
#    destination: /var/www/html/
#hooks:
#  BeforeInstall:
#    - location: scripts/start_server
#      timeout: 300
#      runas: root
#  ApplicationStop:
#    - location: scripts/stop_server
#      timeout: 300
#      runas: root
